# Generated by Django 5.1.2 on 2024-11-07 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('tamanho', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_geral', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_após_plantio', models.IntegerField()),
                ('intervalo_dias', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField()),
                ('tipo_acao', models.CharField(choices=[('Preparo do Solo', 'Preparo do Solo'), ('Plantio', 'Plantio'), ('Irrigação', 'Irrigação'), ('Inspeção', 'Inspeção'), ('Biofertilização', 'Biofertilização'), ('Controle de Pragas', 'Controle de Pragas'), ('Colheita', 'Colheita')], default='Plantio', max_length=50)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ryb_agro_app.cronograma')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.FloatField()),
                ('frequencia', models.CharField(max_length=50)),
                ('data_plantio', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cronograma',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='ryb_agro_app.planta'),
        ),
    ]
