# Generated by Django 5.1.1 on 2024-11-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='celeiro',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='peso_colhido',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='peso_previsto',
        ),
    ]
