# Generated by Django 5.1.1 on 2024-11-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=10)),
                ('data_colheita', models.DateField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colheitas', to='ryb_agro_app.etapa')),
            ],
        ),
    ]
