# Generated by Django 5.1.1 on 2024-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0002_colheita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
