# Generated by Django 5.1.1 on 2024-11-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0002_remove_planta_celeiro_remove_planta_peso_colhido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='celeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='ryb_agro_app.celeiro'),
        ),
        migrations.AddField(
            model_name='planta',
            name='peso_colhido',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='peso_previsto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
    ]
