# Generated by Django 5.1.1 on 2024-10-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0002_remove_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tamanho',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
