# Generated by Django 5.1.3 on 2024-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0003_alter_colheita_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
