# Generated by Django 5.1.1 on 2024-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0003_planta_usuario_cidade_usuario_estado_usuario_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
