# Generated by Django 5.1.1 on 2024-11-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0003_planta_celeiro_planta_peso_colhido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='peso_colhido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='peso_previsto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
