# Generated by Django 5.1.1 on 2024-11-13 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0004_alter_planta_peso_colhido_alter_planta_peso_previsto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluída', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_comerciais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
