# Generated by Django 5.1.1 on 2024-10-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0004_usuario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Nome',
            new_name='nome',
        ),
    ]
