# Generated by Django 5.1.1 on 2024-11-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0005_demandacomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandacomercial',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
