# Generated by Django 5.1.1 on 2024-10-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0006_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='planta',
            name='frequencia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='quantidade',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planta',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
