# Generated by Django 5.1.2 on 2024-11-05 01:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0008_planta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='data_plantio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_geral', models.TextField(blank=True, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='ryb_agro_app.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_após_plantio', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('tipo_acao', models.CharField(choices=[('Preparo do Solo', 'Preparo do Solo'), ('Plantio', 'Plantio'), ('Irrigação', 'Irrigação'), ('Inspeção', 'Inspeção'), ('Biofertilização', 'Biofertilização'), ('Controle de Pragas', 'Controle de Pragas'), ('Colheita', 'Colheita')], default='Plantio', max_length=50)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ryb_agro_app.cronograma')),
            ],
        ),
    ]
