# Generated by Django 5.1.2 on 2024-11-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryb_agro_app', '0010_etapa_intervalo_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='dias_após_plantio',
            field=models.IntegerField(),
        ),
    ]
