name: Build and deploy Python app to Azure Web App - whichteacher

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # Configura o Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Instala Cypress e dependências
      - name: Install Cypress dependencies
        run: |
          npm ci
          npm install cypress wait-on

      # Inicia o servidor Django e executa os testes Cypress
      - name: Run Django server and Cypress tests
        run: |
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000 &
          npx wait-on http://127.0.0.1:8000
          npx cypress run
        env:
          CYPRESS_BASE_URL: http://127.0.0.1:8000

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_948A6F8AF17B48FEA062A6B35D277A9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_621493B248E046489B3502DD6BC49132 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2C9344E88D344B16B38B592EA536C426 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cultivafacil'
          slot-name: 'Production'
          
